# Generated by Django 5.2 on 2025-05-06 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('emissor', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('logo', models.URLField(verbose_name='URL do Logo')),
                ('url_credencial', models.URLField(blank=True, null=True, verbose_name='URL da Credencial')),
                ('id_credencial', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Educacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grau', models.CharField(max_length=100)),
                ('instituicao', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'Educação',
                'verbose_name_plural': 'Educação',
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=100)),
                ('localizacao', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Experiência',
                'verbose_name_plural': 'Experiências',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='HabilidadeTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('básico', 'Básico'), ('intermediário', 'Intermediário'), ('avançado', 'Avançado')], max_length=20)),
            ],
            options={
                'verbose_name': 'Habilidade Técnica',
                'verbose_name_plural': 'Habilidades Técnicas',
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('proficiencia', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
            },
        ),
        migrations.CreateModel(
            name='InformacaoPessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('localizacao', models.CharField(max_length=100)),
                ('linkedin', models.URLField(verbose_name='LinkedIn URL')),
                ('github', models.URLField(verbose_name='GitHub URL')),
                ('sobre', models.TextField()),
                ('disponibilidade', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Informação Pessoal',
                'verbose_name_plural': 'Informações Pessoais',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('descricao', models.TextField()),
                ('descricao_curta', models.CharField(max_length=255)),
                ('imagem', models.ImageField(upload_to='projetos/')),
                ('repo_url', models.URLField(verbose_name='URL do Repositório')),
                ('demo_url', models.URLField(blank=True, null=True, verbose_name='URL da Demonstração')),
                ('iframe_url', models.URLField(blank=True, null=True, verbose_name='URL do iframe')),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='SoftSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Soft Skill',
                'verbose_name_plural': 'Soft Skills',
            },
        ),
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('info_pessoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesses', to='portfolio.informacaopessoal')),
            ],
            options={
                'verbose_name': 'Interesse',
                'verbose_name_plural': 'Interesses',
            },
        ),
        migrations.CreateModel(
            name='ResponsabilidadeExperiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('experiencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsabilidades', to='portfolio.experiencia')),
            ],
            options={
                'verbose_name': 'Responsabilidade',
                'verbose_name_plural': 'Responsabilidades',
            },
        ),
        migrations.CreateModel(
            name='TagCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('certificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='portfolio.certificado')),
            ],
            options={
                'verbose_name': 'Tag de Certificado',
                'verbose_name_plural': 'Tags de Certificados',
            },
        ),
        migrations.CreateModel(
            name='TagProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='portfolio.projeto')),
            ],
            options={
                'verbose_name': 'Tag de Projeto',
                'verbose_name_plural': 'Tags de Projetos',
            },
        ),
        migrations.CreateModel(
            name='TecnologiaExperiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('experiencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnologias', to='portfolio.experiencia')),
            ],
            options={
                'verbose_name': 'Tecnologia',
                'verbose_name_plural': 'Tecnologias',
            },
        ),
    ]
