# Generated by Django 5.2 on 2025-05-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='iframe_url',
        ),
        migrations.AlterField(
            model_name='projeto',
            name='demo_url',
            field=models.URLField(blank=True, help_text='URL para demonstração do projeto. Esta URL também será usada no iframe de visualização.', null=True, verbose_name='URL da Demonstração/iframe'),
        ),
    ]
